version: '3.8'

services:
  php:
    build: .
    ports:
      - "8000:9000"
    environment:
      APP_ENV: prod
      DATABASE_URL: ${DATABASE_URL}
      MONGODB_URL: ${MONGODB_URL}
      JWT_PASSPHRASE: ${JWT_PASSPHRASE}
      CORS_ALLOW_ORIGIN: ${CORS_ALLOW_ORIGIN}
    volumes:
      - .:/var/www/html

  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecoride
      MYSQL_USER: anastasia
      MYSQL_PASSWORD: OneLove24!
    ports:
      - "3307:3306"  
    volumes:
      - mysql_data:/var/lib/mysql

  mongo:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
      MONGO_DATABASE: ecoride_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mysql_data:
  mongo_data:
