<?php

namespace ContainerOIEv37w;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTripReservationControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\TripReservationController' shared autowired service.
     *
     * @return \App\Controller\TripReservationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/TripReservationController.php';

        $container->services['App\\Controller\\TripReservationController'] = $instance = new \App\Controller\TripReservationController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));

        $instance->setContainer(($container->privates['.service_locator.h_6y.b1'] ?? $container->load('get_ServiceLocator_H6y_B1Service'))->withContext('App\\Controller\\TripReservationController', $container));

        return $instance;
    }
}
