<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Car extends \App\Entity\Car implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'availableSeats' => [parent::class, 'availableSeats', null, 16],
        "\0".parent::class."\0".'brand' => [parent::class, 'brand', null, 16],
        "\0".parent::class."\0".'color' => [parent::class, 'color', null, 16],
        "\0".parent::class."\0".'customPreferences' => [parent::class, 'customPreferences', null, 16],
        "\0".parent::class."\0".'fuelType' => [parent::class, 'fuelType', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'licensePlate' => [parent::class, 'licensePlate', null, 16],
        "\0".parent::class."\0".'model' => [parent::class, 'model', null, 16],
        "\0".parent::class."\0".'registrationDate' => [parent::class, 'registrationDate', null, 16],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null, 16],
        'availableSeats' => [parent::class, 'availableSeats', null, 16],
        'brand' => [parent::class, 'brand', null, 16],
        'color' => [parent::class, 'color', null, 16],
        'customPreferences' => [parent::class, 'customPreferences', null, 16],
        'fuelType' => [parent::class, 'fuelType', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'licensePlate' => [parent::class, 'licensePlate', null, 16],
        'model' => [parent::class, 'model', null, 16],
        'registrationDate' => [parent::class, 'registrationDate', null, 16],
        'user' => [parent::class, 'user', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
